version: '3.1'
services:
  web:
    restart: always
    image: odoo-skeleton
    container_name: dev-16
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - $PWD/config:/etc/odoo
      - $PWD/addons:/usr/lib/python3/dist-packages/odoo/extra-addons
      - $PWD/enterprise:/usr/lib/python3/dist-packages/odoo/enterprise
      - $PWD/.vscode:/usr/lib/python3/dist-packages/odoo/.vscode
  db:
    restart: always
    image: postgres:13
    container_name: ps13-dev-16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
